# 30th april - NUMPY

In [3]:
import numpy as np 

In [7]:
np.__version__   # to know the version of numpy 

'1.26.4'

In [9]:
import sys
sys.version


'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

# creating arrays

In [12]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [14]:
type(my_list)

list

# below code we are converting list to array 

In [19]:
arr = np.array(my_list)  #pip install 

In [21]:
arr

array([0, 1, 2, 3, 4, 5])

In [23]:
type(arr)

numpy.ndarray

In [27]:
np.arange(10)       # it will give as between the numbers 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(3.0)

array([0., 1., 2.])

In [31]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [33]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [37]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [39]:
np.arange(20,10)   # 1st > 2nd   1st argument should be lessthan 2nd argument 

array([], dtype=int32)

In [41]:
np.arange(-20,9)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8])

In [43]:
np.arange(-20,-11)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12])

In [45]:
ar = np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [49]:
np.arange(10,30,5)   # 10th strt point , 30 - end point , 5 step 

array([10, 15, 20, 25])

In [51]:
np.zeros(10)   # parameter tuning - system uses his own parameter 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [55]:
np.zeros(10,dtype=int)   # hyperparameter tuning 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [61]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [63]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [65]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [67]:
np.zeros((10,30),dtype=int)   # converting into int

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [69]:
np.zeros((10,10),dtype=int)  

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [71]:
np.ones(3)

array([1., 1., 1.])

In [73]:
np.ones(4,dtype=int) 

array([1, 1, 1, 1])

In [75]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [77]:
np.twos((2,3))  # only zeros and ones worked 

AttributeError: module 'numpy' has no attribute 'twos'

In [79]:
rand(3,2)

NameError: name 'rand' is not defined

In [81]:
random.rand(3,2)

NameError: name 'random' is not defined

In [90]:
np.random.rand(5)    # np-package , random - module , rand - function 

array([0.05514041, 0.17911373, 0.91296505, 0.14167329, 0.14926403])

In [92]:
np.random.rand(3,2)

array([[0.8050842 , 0.78039999],
       [0.33757329, 0.58202768],
       [0.32322589, 0.09254777]])

In [94]:
np.random.rand(5,6)

array([[0.99148576, 0.06583702, 0.15279467, 0.43252993, 0.60159376,
        0.31178197],
       [0.44802607, 0.25664963, 0.37591672, 0.77189073, 0.24948012,
        0.31096593],
       [0.07337549, 0.8308405 , 0.67880891, 0.08465141, 0.2613934 ,
        0.13664831],
       [0.98426216, 0.03716581, 0.55439938, 0.15491317, 0.8253711 ,
        0.58968455],
       [0.7081951 , 0.97568512, 0.11140706, 0.25219379, 0.58309133,
        0.7542637 ]])

In [104]:
np.random.randint(4,6)     # it willl give 4 or 5 it will not give 6 it is high value 

5

In [113]:
np.random.randint(2,20)    

9

In [122]:
np.random.randint(2,20,5)      # we need 5 values 

array([16,  9,  6, 13,  3])

In [126]:
np.random.randint(2,20,4)    

array([11,  2,  4,  9])

In [128]:
np.random.randint(10,40,(10,10))

array([[36, 20, 38, 31, 25, 21, 15, 24, 22, 38],
       [10, 18, 21, 39, 35, 22, 32, 21, 21, 18],
       [25, 29, 21, 37, 16, 25, 16, 38, 39, 16],
       [38, 26, 11, 19, 17, 28, 20, 29, 12, 21],
       [33, 11, 18, 12, 30, 22, 23, 15, 26, 38],
       [14, 10, 16, 17, 22, 39, 15, 22, 15, 35],
       [38, 17, 20, 11, 16, 21, 33, 13, 25, 15],
       [35, 16, 19, 24, 24, 22, 13, 14, 39, 34],
       [23, 10, 38, 31, 11, 24, 10, 16, 20, 25],
       [18, 35, 34, 25, 37, 22, 20, 23, 22, 26]])

In [136]:
np.random.randint(10,30,(12,12))

array([[27, 15, 29, 14, 23, 10, 19, 14, 23, 24, 25, 12],
       [29, 22, 11, 24, 21, 29, 15, 18, 11, 14, 11, 19],
       [18, 12, 25, 18, 12, 18, 23, 11, 11, 24, 16, 20],
       [18, 25, 17, 12, 18, 19, 20, 26, 25, 21, 28, 16],
       [26, 26, 13, 27, 12, 27, 28, 17, 26, 12, 21, 14],
       [28, 27, 22, 27, 14, 25, 13, 12, 16, 21, 25, 15],
       [14, 11, 22, 25, 14, 22, 15, 12, 16, 14, 26, 27],
       [23, 27, 18, 24, 15, 17, 11, 11, 18, 24, 10, 15],
       [15, 21, 25, 29, 25, 17, 18, 26, 17, 23, 18, 25],
       [12, 12, 16, 29, 12, 13, 19, 10, 29, 16, 11, 11],
       [21, 28, 15, 13, 24, 16, 11, 10, 24, 19, 23, 25],
       [25, 19, 16, 29, 27, 23, 27, 12, 13, 15, 12, 25]])

In [140]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [142]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [144]:
np.arange(1,13).reshape(5,4)     # 

ValueError: cannot reshape array of size 12 into shape (5,4)

In [146]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [150]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

# slicing in matrix

In [153]:
b = np.random.randint(10,20,(5,4))

In [155]:
b

array([[16, 16, 15, 16],
       [12, 16, 14, 18],
       [19, 17, 19, 14],
       [12, 15, 17, 10],
       [10, 15, 13, 18]])

In [157]:
type(b)

numpy.ndarray

In [159]:
b

array([[16, 16, 15, 16],
       [12, 16, 14, 18],
       [19, 17, 19, 14],
       [12, 15, 17, 10],
       [10, 15, 13, 18]])

In [161]:
b[:]

array([[16, 16, 15, 16],
       [12, 16, 14, 18],
       [19, 17, 19, 14],
       [12, 15, 17, 10],
       [10, 15, 13, 18]])