USES OF NUMPY - arthimetic operations , statistical operations , bitwise operrations , copying and viewing arrays , stacking , searching , sorting and counting , mathematical operations , broadcasting , linearalgebra, matrix operations 

# Array Creation Functions 

In [2]:
import numpy as np 

In [4]:
a = np.array([1,2,3])
print("Array a:",a)

Array a: [1 2 3]


In [6]:
b = np.arange(0,10,2)    #values from 0 to 10 with step 2
print("Array b:",b)

Array b: [0 2 4 6 8]


In [10]:
c = np.linspace(0,1,5)    # 5 values evenly spaced btw 0 and 1 
print('Array c:', c)

Array c: [0.   0.25 0.5  0.75 1.  ]


In [18]:
d = np.zeros((2,3))
print("Array d:\n",d)

Array d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [14]:
e = np.ones((3,2))     # 3 x 2 array of ones 
print("Array e:\n",e)

Array e:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [16]:
f = np.eye(4)        # 4 x 4 identity matrix daigonals will be 1 
print("Identity matrix f:\n",f)

Identity matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# ARRAY MAUPLATION FUNCTIONS 

In [21]:
a1 = np.array([1,2,3])
reshaped = np.reshape(a1 ,(1,3))    # reshape 1 x 3
print("Reshaped array:",reshaped)

Reshaped array: [[1 2 3]]


In [23]:
f1 = np.array([[1,2],[3,4]])
flattened = np.ravel(f1)     # flattened to 1d array 
print('flattend array:',flattened)

flattend array: [1 2 3 4]


In [25]:
e1 = np.array([[1,2] , [3,4]])
transposed = np.transpose(e1)        # transpose the array 
print("transposed array:\n",transposed)

transposed array:
 [[1 3]
 [2 4]]


In [27]:
a2 = np.array([1,2])
b2 = np.array([3,4])
stacked = np.vstack([a2,b2])    # stack a nad b are vertically 
print("stacked array:\n",stacked)

stacked array:
 [[1 2]
 [3 4]]


# mathematical functions 

In [30]:
# add two arrays 
g = np.array([1,2,3,4])
added = np.add(g,2)       # add 2 to each element 
print("Added 2 to g:" , added)

Added 2 to g: [3 4 5 6]


In [38]:
# sqquare ecah element 
squared = np.power(g,2)
print("squared g:",squared)

squared g: [ 1  4  9 16]


In [40]:
sqrt_val = np.sqrt(g)   # squarerot of each element 
print("square root of g:" , sqrt_val)

square root of g: [1.         1.41421356 1.73205081 2.        ]


In [42]:
print(a1)
print(g)


[1 2 3]
[1 2 3 4]


In [44]:
# dOT PRODUCT of two arrays
a2 = np.array([1,2,3])
dot_product = np.dot(a2,g)
print("Dot product of a and g:", dot_product)

ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

In [46]:
print(a)
print(a1)


[1 2 3]
[1 2 3]


In [48]:
a3 = np.array([1,2,3])   # multipy and add 
dot_product = np.dot(a1,a)
print("Dot product of a1 and a:",dot_product)

Dot product of a1 and a: 14


# STATISTICAL FUNCTIONS 

In [53]:
s = np.array([1,2,3,4])  # average 
mean = np.mean(s)
print("Mean of s:",mean)

Mean of s: 2.5


In [55]:
std_dev = np.std(s)         # standard deviation 1 - 2.5 square dived by element number 
print("Standard deviation of s:", std_dev)

Standard deviation of s: 1.118033988749895


In [57]:
# min eleemnt of an array 
minimum = np.min(s)
print("standard deviation of s:",std_dev)

standard deviation of s: 1.118033988749895


In [59]:
minimum = np.min(s)
print("min of s:",minimum)

min of s: 1


In [63]:
maximum = np.max(s)
print("max of s:",maximum)

max of s: 4


# LINEAR ALGEBRA FUNCTIONS 

In [66]:
# CREATE  a matrix
matrix = np.array([[1,2],[3,4]])

In [70]:
# determinant of matrix 
determinant = np.linalg.det(matrix)
print("Determinant of matrix:",determinant)

Determinant of matrix: -2.0000000000000004


In [76]:
# Inversse of a matrix 
inverse = np.linalg.inv(matrix)
print("Inverse of matrix:\n" , inverse)

Inverse of matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]


# random sampling functions 

In [79]:
# generate random valuyes betw 0 and 1 
random_vals = np.random.rand(3)
print("Random values:",random_vals)

Random values: [0.48551208 0.21282446 0.45041757]


In [85]:
# set seed for reproducibility 
np.random.seed(0)
random_vals = np.random.rand(3)
print("Random values:",random_vals)

Random values: [0.5488135  0.71518937 0.60276338]


In [91]:
rand_ints = np.random.randint(0,10,size=5)
print("Random integers:",rand_ints)

Random integers: [8 1 6 7 7]


# BOOLEAN & LOGICAL FUNCTIONS 

In [104]:
# check if all elements are true 
# all
logical_test = np.array([True,False,True])
all_true = np.all(logical_test)
print("All elements are True:",all_true)

All elements are True: False


In [98]:
logical_test = np.array([False,False,False])
all_true = np.all(logical_test)
print("All elements are True:",all_true)

All elements are True: False


In [102]:
any_true = np.any(logical_test)
print("Any elements are True:",any_true)

Any elements are True: True


# SET OPERATIONS 

In [111]:
# INTERSECTION of two arrays 
set_a = np.array([1,2,3,4])
set_b = np.array([3,4,5,6])
intersection = np.intersect1d(set_a,set_b)
print("intersection of a and b:", intersection)

intersection of a and b: [3 4]


In [113]:
union = np.union1d(set_a,set_b)
print("Union of a and b:",union)

Union of a and b: [1 2 3 4 5 6]


# ARRAY ATTRIBUTE FUNCTIONS

In [116]:
# array attributes
a = np.array([1,2,3])
shape = a.shape    # shape of the array 
size = a.size        # numver of elements 
dimensions = a.ndim    # number of dimensions 
dtype = a.dtype  # datatype of the array 
print("shape of a:",shape)
print("size of a:",size)
print("Number of dimensionsof a:",dimensions)
print("Data type of a:",dtype)

shape of a: (3,)
size of a: 3
Number of dimensionsof a: 1
Data type of a: int32


# OTHER FUNCTIONS 

In [119]:
# create a copy of an array 
a = np.array([1,2,3])
copied_array = np.copy(a)
print("copied array:",copied_array)

copied array: [1 2 3]


In [121]:
array_size_in_bytes = a.nbytes     # size in bytes 1 bit = 0.125 bytes 
print("Size of a in bytes:",array_size_in_bytes)

Size of a in bytes: 12


In [123]:
shared = np.shares_memory(a,copied_array)   # check if two arrays shares memory
print("Do a and copied_array share memory?",shared)

Do a and copied_array share memory? False


# THANK YOU 